# Generated by Django 4.2 on 2023-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='correo@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
